-- liquibase formatted sql

-- changeset Mihail:1

CREATE TABLE socks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color       VARCHAR(255) NOT NULL,
    cotton_part INTEGER      NOT NULL,
    name        VARCHAR(255) NOT NULL,
    quantity    INTEGER      NOT NULL
);