-- liquibase formatted sql

-- changeset Mihail:1

CREATE TABLE socks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    color       VARCHAR(255),
    cotton_part INTEGER,
    quantity    INTEGER
);